// Generate static CSS assets from the pinned tailwindcss package — never
// hand-written, so they cannot drift. Run: pnpm gen:assets (after bumping
// the tailwindcss dev-dependency).
//
//   assets/theme.mjs     — full default theme flattened to :root (via the real
//                          compiler with `@theme static`) incl. @keyframes,
//                          plus the deprecated inline-reference values as data
//   assets/preflight.mjs — v4 preflight via the real compiler (resolves the
//                          build-time `--theme(...)` calls to their
//                          `var(--default-*, fallback)` form; shipped verbatim
//                          they are invalid CSS and browsers drop the
//                          declarations — body text fell back to serif)
//   assets/prose.mjs     — `prose` compiled from @tailwindcss/typography
//                          (opt-in: pass to createEngine({ proseCss }))
//   assets/index.mjs     — engine + assets entry (size measurement target;
//                          prose excluded, it is opt-in)
import { compile } from "tailwindcss";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));
const assets = path.resolve(here, "../assets");
mkdirSync(assets, { recursive: true });

const twVersion = require("tailwindcss/package.json").version;
const themeSrc = readFileSync(require.resolve("tailwindcss/theme.css"), "utf8");
const preflight = readFileSync(
  require.resolve("tailwindcss/preflight.css"),
  "utf8",
);

// Full flattened :root via the real compiler: `static` emits every theme var
// and keyframe regardless of usage. The deprecated `inline reference` block is
// excluded (those values are inlined at compile time, never emitted).
const staticTheme = themeSrc.replace(/@theme default \{/, "@theme static {");
const compiled = await compile(staticTheme, {
  base: "/",
  async loadStylesheet() {
    throw new Error("gen-assets: no imports");
  },
  async loadModule() {
    throw new Error("gen-assets: no modules");
  },
});
const themeCss = compiled.build([]).replace(/^\/\*![^\n]*\n/, "");

// Preflight through the real compiler, with the default theme in context, so
// `--theme(--default-font-family, <stack>)` resolves exactly as in a real v4
// build: `var(--default-font-family, <stack>)`, overridable via the theme
// (theme.mjs ships `--default-font-family: var(--font-sans)`). The emitted
// :root theme block is stripped — the theme asset already ships every var.
const preflightCompiled = await compile(`${themeSrc}\n${preflight}`, {
  base: "/",
  async loadStylesheet() {
    throw new Error("gen-assets: no imports");
  },
  async loadModule() {
    throw new Error("gen-assets: no modules");
  },
});
const preflightCss = preflightCompiled
  .build([])
  .replace(/^\/\*![^\n]*\n/, "")
  .replace(/^:root, :host \{[\s\S]*?\n\}\n/, "");
if (/--theme\(/.test(preflightCss))
  throw new Error("preflight still contains unresolved --theme() calls");
if (!/html[\s\S]{0,200}font-family: var\(--default-font-family/.test(preflightCss))
  throw new Error("preflight html font-family did not resolve to var() form");

// Deprecated inline-reference values (e.g. bare --shadow, --radius): parse
// them out of the source block so the engine can inline them like v4 does.
const inlineBlock = themeSrc.match(
  /@theme default inline reference \{([\s\S]*?)\n\}/,
);
const inlineVars = {};
if (inlineBlock) {
  for (const m of inlineBlock[1].matchAll(/(--[\w-]+):\s*([^;]+);/g)) {
    inlineVars[m[1]] = m[2].replace(/\s+/g, " ").trim();
  }
}

// `prose` from the real typography plugin via the real compiler. The theme
// vars in the output are stripped (the theme asset already ships them all).
const typoVersion = require("@tailwindcss/typography/package.json").version;
const proseCompiled = await compile(
  `${themeSrc}\n@plugin "@tailwindcss/typography";\n@tailwind utilities;`,
  {
    base: path.dirname(require.resolve("tailwindcss/package.json")),
    async loadStylesheet() {
      throw new Error("gen-assets: no stylesheet imports");
    },
    async loadModule(id) {
      return {
        path: require.resolve(id),
        base: "/",
        module: (await import(require.resolve(id))).default,
      };
    },
  },
);
const proseCss = proseCompiled
  .build(["prose"])
  .replace(/^\/\*![^\n]*\n/, "")
  .replace(/^:root, :host \{[\s\S]*?\n\}\n/, "");
if (!proseCss.includes(".prose")) throw new Error("prose CSS came out empty");

const banner = (what) =>
  `// GENERATED by scripts/gen-assets.mjs from tailwindcss@${twVersion} — do not edit.\n// ${what}\n`;

writeFileSync(
  path.join(assets, "theme.mjs"),
  banner("Default theme flattened to :root, plus keyframes.") +
    `export const themeCss = ${JSON.stringify(themeCss)};\n` +
    `export const inlineThemeVars = ${JSON.stringify(inlineVars, null, 2)};\n`,
);
writeFileSync(
  path.join(assets, "preflight.mjs"),
  banner("v4 preflight, compiled (--theme() resolved).") +
    `export const preflightCss = ${JSON.stringify(preflightCss)};\n`,
);
writeFileSync(
  path.join(assets, "prose.mjs"),
  `// GENERATED by scripts/gen-assets.mjs from tailwindcss@${twVersion} + @tailwindcss/typography@${typoVersion} — do not edit.\n` +
    `// Opt-in: createEngine({ proseCss }) injects it on the first \`prose\` token.\n` +
    `export const proseCss = ${JSON.stringify(proseCss)};\n`,
);
writeFileSync(
  path.join(assets, "index.mjs"),
  `// Engine + static assets: the "engine+assets" size-budget target.\n` +
    `// (prose is opt-in and deliberately not part of this budget.)\n` +
    `export * from "../src/index.ts";\n` +
    `export { themeCss, inlineThemeVars } from "./theme.mjs";\n` +
    `export { preflightCss } from "./preflight.mjs";\n`,
);
console.log(
  `generated assets from tailwindcss@${twVersion}: theme ${themeCss.length} chars, preflight ${preflight.length} chars, prose ${proseCss.length} chars (typography@${typoVersion}), ${Object.keys(inlineVars).length} inline vars`,
);
